### ISSUE TITLE
non-collection @Relation(s)

### ISSUE THREAD

**Issue by bthj** [arangodb/spring-data#104]
Is something like this possible?
```
@Relations(edges = DepartureToItinerary.class)
private Itinerary itinerary;
```
or does it always have to be a collection, like
```
@Relations(edges = DepartureToItinerary.class)
private List<Itinerary> itineraries;
```

If I'm sure there will always be just one itinerary linked to the document, what would be the best / a good approach?

**Comment by christian-lechner** [comment]
This is currently not supported - it would throw an `UnsupportedOperationException`. I'll come back to you tomorrow and give you more info.

**Comment by bthj** [comment]
Thanks :)

**Comment by christian-lechner** [comment]
@bthj currently you need to use a collection for `@Relations` fields, but we've added this feature to our enhancement list.

**Comment by bthj** [comment]
Great!

For now I've got the desired results by changing the getter/setter for the `@Relations` attribute to `private` and then adding a corresponding _singular_ attribute, whose getter utilizes the corresponding collection (e.g. `getItinerary()` returns the first element from `itineraries`, if available).

**Comment by christian-lechner** [comment]
Why do you need private getter/setter methods for `itineraries` and a singular attribute? A `itineraries` field and a `getItineraray()` and `setItinerary(..)` that access the `itineraries` list should be enough.

Btw: Which version of Spring Data ArangoDB do you use?

**Comment by bthj** [comment]
Ah, of course - that's simpler :)

I'm still on 1.1.5 - I tried upgrading but got errors when upserting, saving documents with the id set, saying the document didn't exist, maybe I need to set the key also, will try that tomorrow...

**Comment by mpv1989** [comment]
Hi @bthj,

I implemented the requested feature. It will be available with version 3.0.0. You can already test it with the current 3.0.0-SNAPSHOT.

best
Mark

**Comment by mpv1989** [comment]
I started the release process of `3.0.0-RC.1` right now. Should be available later today.

**Comment by bthj** [comment]
Thanks @mpv1989.  

I'm in the process of upgrading to `3.0.0-RC.1` (can now upgrade to Spring Boot 2 as my Apache Camel dependency now supports it).  For custom IDs I've implemented the `Persistable` interface of Spring Data, as @christian-lechner suggested.

One other behaviour is different from when I was at Spring Data ArangoDB version 1.1.5:

Let's say I have a SoundToTag `@Edge` class and to ensure I don't create multiple edges relating the same documents, I have code like:
```
Optional<SoundToTag> soundToTagEdge = soundToTagRepository.findBySoundAndTag(sound.getId(), tag.getId());
if( ! soundToTagEdge.isPresent() ) {
    soundToTagRepository.save(new SoundToTag(sound, tag));
}
```
This worked correctly to prevent multiple edges between the same documents on `1.1.5` but after upgrading to `3.0.0-RC.1` I get new edges after each run.  How should I approach this differently now?

**Comment by mpv1989** [comment]
Hi @bthj,

with `3.0.0-RC.1` a field annotated with `@Id` is saved as `_key` instead of `_id` (as in `1.1.5`). We changed this to fit better into the design of Spring Data, which also allow us to use non-String ids.

To still be able to work with `_id` we implemented the annotation `@ArangoId` which is what you need for your use case, because you want to compare `_id` with your `_from` and `_to` values in your edge.
```
@Document
public class Sound {
    @ArangoId private String arangoId; // persisted as _id
    @Id private String id; // persisted as _key
}
```
```
@Edge
public class SoundToTag {
    @From Sound sound; // persisted as _from
    @To Tag tag; // persisted as _to
}
```
```
Optional<SoundToTag> soundToTagEdge = soundToTagRepository.findBySoundAndTag(sound.getArangoId(), tag.getArangoId());
if( ! soundToTagEdge.isPresent() ) {
    soundToTagRepository.save(new SoundToTag(sound, tag));
}
```

**Note**: The field annotated with `@ArangoId` will not be persisted in the database. It only exists for reading purposes.

**Comment by bthj** [comment]
But to the original topic, I'm finally trying the `@Relations` annotation with non-collections on `3.0.0-RC.1` but am stuck on a Jackson error for the returned data.  I've had similar issues before which have been solved with `@JsonIgnoreProperties`, but now it's not doing the trick:

E.g. in `Trip` there is
```
@Relations(edges = TripToDriver.class, lazy = true)
@JsonIgnoreProperties("trips")
private Driver driver;
```
and in `Driver` there is
```
@Relations(edges = TripToDriver.class, lazy = true)
@JsonIgnoreProperties("driver")
private List<Trip> trips;
```
which results in the following error from a REST/Jackson endpoint:
`com.fasterxml.jackson.databind.JsonMappingException: java.lang.reflect.InvocationTargetException (through reference chain: com.sun.proxy.$Proxy155[0]->...Trip["driver"]->...Driver$$EnhancerByCGLIB$$7c3531a6["entity"]->...Driver["trips"] ...`

Any idea how this can be circumvented?

**Comment by christian-lechner** [comment]
This happens because the proxy classes that are created if you set `lazy=true` now implement the `LazyLoadingProxy` interface. This interface offers two methods, `getEntity()` and `getRefId()`, that are serialized by Jackson as `entity` and `refId`. 

You can see this in the reference chain you posted (notice the `Driver` proxy class `Driver$$EnhancerByCGLIB`):
```
Trip["driver"]->Driver$$EnhancerByCGLIB$$7c3531a6["entity"]->Driver["trips"]
```
Your `@JsonIgnoreProperties` annotations do not work because for Jackson there is no `trips` or `driver` property present (only `entity` and `refId` from the proxy). So you get again an infinite recursion.

To fix this and to get a correctly serialized output (without a wrapper object from the proxy) you need to create a custom serializer and register it on your `ObjectMapper`:

```java
public class LazyLoadingProxySerializer extends JsonSerializer<LazyLoadingProxy> {

	@Override
	public void serialize(LazyLoadingProxy proxy, JsonGenerator jgen, SerializerProvider sp)
			throws IOException {
		sp.defaultSerializeValue(proxy.getEntity(), jgen);
	}

}
```

**Comment by bthj** [comment]
Adding the custom `LazyLoadingProxySerializer` and registering it on a `@Document` class with
`@JsonSerialize(using = LazyLoadingProxySerializer.class)`
results in:
`com.fasterxml.jackson.databind.JsonMappingException: ....Document cannot be cast to com.arangodb.springframework.core.convert.resolver.LazyLoadingProxy`

The `extends StdSerializer<LazyLoadingProxy>` part of the serializer definition seems to suggest the Document class should implement that interface, and if I do that and overload the required methods, like so:
```
@Override
public String getRefId() {
    return arangoId;
}

@Override
public Object getEntity() {
    return this;
}
```
the results are:
```
java.lang.StackOverflowError
	at com.fasterxml.jackson.databind.util.TypeKey.typedHash(TypeKey.java:53)
	at com.fasterxml.jackson.databind.ser.impl.ReadOnlyClassToSerializerMap.typedValueSerializer(ReadOnlyClassToSerializerMap.java:85)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:702)
	at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:1033)
	at ....LazyLoadingProxySerializer.serialize(LazyLoadingProxySerializer.java:19)
```
Do you spot what is amiss?

**Comment by bthj** [comment]
Thanks.  Now I'm rid of that StackOverflowError at LazyLoadingProxySerialize, but then for the Collection `@Relation`s, I'm getting that infinite recursion error, where things were fine before, such as results including:
```
@Document
public class Departure {
    @Relations(edges = DepartureToBooking.class, lazy = true)
    @JsonIgnoreProperties("departures")
    private List<Booking> bookings;
...
```
and
```
@Document
public class Booking {
    @Relations(edges = DepartureToBooking.class, lazy = true)
    @JsonIgnoreProperties("bookings")
    private List<Departure> departures;
...
```
give:
`com.fasterxml.jackson.databind.JsonMappingException: java.lang.reflect.InvocationTargetException (through reference chain: java.util.ArrayList[0]->is...entity.document.Departure["bookings"]->java.util.ArrayList[0]->is...entity.document.Booking["departures"]->...`

If I try removing `lazy = true` from the `@Relation`s, the results are:
```
org.springframework.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
	at org.springframework.objenesis.instantiator.sun.SunReflectionFactoryHelper.newConstructorForSerialization(SunReflectionFactoryHelper.java:54)
	at org.springframework.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.<init>(SunReflectionFactoryInstantiator.java:41)
	at org.springframework.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:68)
	at org.springframework.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:94)
	at org.springframework.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at com.arangodb.springframework.core.convert.resolver.AbstractResolver.proxy(AbstractResolver.java:89)
	at com.arangodb.springframework.core.convert.resolver.RelationsResolver.resolveOne(RelationsResolver.java:50)
```

As I'm on Spring Boot, I registered the serializer within a `@Configuration` class:
```
import com.arangodb.springframework.core.convert.resolver.LazyLoadingProxy;
import com.fasterxml.jackson.core.Version;
import com.fasterxml.jackson.databind.Module;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleSerializers;
import is...LazyLoadingProxyMixIn;
import is...LazyLoadingProxySerializer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class JacksonConfiguration {

    @Bean
    public ObjectMapper objectMapper() {
        final ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new Module() {
            @Override
            public String getModuleName() {
                return "Lazy Loading Proxy";
            }

            @Override
            public Version version() {
                return Version.unknownVersion();
            }

            @Override
            public void setupModule(final SetupContext context) {
                final SimpleSerializers ser = new SimpleSerializers();
                ser.addSerializer(new LazyLoadingProxySerializer());
                context.addSerializers(ser);
            }

        });
        mapper.addMixIn( LazyLoadingProxy.class, LazyLoadingProxyMixIn.class );
        return mapper;
    }
}
```

**Comment by christian-lechner** [comment]
Please notice what I've written above:
> But this won't work in your case, since you want to use `@JsonIgnoreProperties` on fields. Please see my updated answer above.

**The custom `LazyLoadingProxySerializer` does not work in your case.** The `mapper.registerModule...` code example was just to show **how you should have done it if this approach would work**. That's why I also removed the serializer code from my first answer. I'm sorry for the confusion.

You only need to do the following:
```java
@Configuration
public class JacksonConfiguration {

    @Bean
    public ObjectMapper objectMapper() {
        final ObjectMapper mapper = new ObjectMapper();
        mapper.addMixIn(LazyLoadingProxy.class, LazyLoadingProxyMixIn.class);
        return mapper;
    }
}
```

**Comment by bthj** [comment]
Ah, now I got it and now it's working :)  Thanks again!

**Comment by bthj** [comment]
To make make this thread a bit longer, one more question which is remotely related to the issue:

In an [example project](https://github.com/mpv1989/stackoverflow-51597981) @mpv1989  created [in response to a StackOverflow question](https://stackoverflow.com/a/51783399/169858) I noticed he uses [Lombok @Data](https://projectlombok.org/features/Data) to get rid of getters/setters etc., so I decided to give it a try, with good results, except for properties circularly annotated with `@Relations` (e.g. bookings in Departure and departures in Booking), I had to add `@EqualsAndHashCode.Exclude @ToString.Exclude`, otherwise I'd get errors like:
```
at com.sun.proxy.$Proxy161.toString(Unknown Source) ~[na:na]
at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_66]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_66]
at is...entity.document.Booking.toString(Booking.java:17) ~[classes/:na]
at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_66]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_66]
at java.util.AbstractCollection.toString(AbstractCollection.java:462) ~[na:1.8.0_66]
at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
at com.arangodb.springframework.core.convert.resolver.AbstractResolver$ProxyInterceptor.intercept(AbstractResolver.java:145) ~[arangodb-spring-data-3.0.0-RC.1.jar:na]
at com.arangodb.springframework.core.convert.resolver.AbstractResolver$ProxyInterceptor.invoke(AbstractResolver.java:129) ~[arangodb-spring-data-3.0.0-RC.1.jar:na]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
at com.sun.proxy.$Proxy161.toString(Unknown Source) ~[na:na]
at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_66]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_66]
at is...entity.document.Departure.toString(Departure.java:21) ~[classes/:na]
at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_66]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_66]
at java.util.AbstractCollection.toString(AbstractCollection.java:462) ~[na:1.8.0_66]
at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
at com.arangodb.springframework.core.convert.resolver.AbstractResolver$ProxyInterceptor.intercept(AbstractResolver.java:145) ~[arangodb-spring-data-3.0.0-RC.1.jar:na]
at com.arangodb.springframework.core.convert.resolver.AbstractResolver$ProxyInterceptor.invoke(AbstractResolver.java:129) ~[arangodb-spring-data-3.0.0-RC.1.jar:na]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
at com.sun.proxy.$Proxy161.toString(Unknown Source) ~[na:na]
at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_66]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_66]
```
So it works fine including those `@EqualsAndHashCode.Exclude @ToString.Exclude` annotations along with `@Relations` but I just wonder if I could do something differently, as they are a bit of a clutter (and I tried `@Data` to lessen the boilerplate : )
