### ISSUE TITLE
Cannot register a converter which is declared as a lambda expression

### ISSUE THREAD

**Issue by gbyczyns** [arangodb/spring-data#120]
I'm trying to register a custom converter:
```java
@Configuration
@EnableArangoRepositories(basePackages = { "com.mycompany.myproject" })
public class ArangoConfiguration extends AbstractArangoConfiguration {
	@Override
	protected CustomConversions customConversions() {
		Converter<String, LocalTime> localTimeConverter = source -> LocalTime.parse(source);
		return new ArangoCustomConversions(List.of(localTimeConverter));
	}
}
```

But this fails with an exception:
```java
Caused by: java.lang.IllegalStateException: Couldn't resolve type arguments for class com.mycompany.myproject.ArangoConfiguration$$Lambda$681/564218949!
	at org.springframework.data.convert.CustomConversions$StoreConversions.getRegistrationFor(CustomConversions.java:590)
	at org.springframework.data.convert.CustomConversions$StoreConversions.getRegistrationsFor(CustomConversions.java:576)
	at org.springframework.data.convert.CustomConversions.lambda$new$3(CustomConversions.java:119)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.springframework.data.convert.CustomConversions.<init>(CustomConversions.java:120)
	at com.arangodb.springframework.core.convert.ArangoCustomConversions.<init>(ArangoCustomConversions.java:52)
...
```

A simple workaround is to don't use lambda:
```java
	@Override
	protected CustomConversions customConversions() {
		Converter<String, LocalTime> localTimeConverter = new Converter<String, LocalTime>() {
			@Override
			public LocalTime convert(String source) {
				return LocalTime.parse(source);
			}
		};
		return new ArangoCustomConversions(List.of(localTimeConverter));
	}
```

**Comment by christian-lechner** [comment]
There is currently no way in Java to get type arguments from lambdas. So you need to stick with the anonymous class solution.
