### ISSUE TITLE
Not possible to read existing data with new fields in entity

### ISSUE THREAD

**Issue by lotabout** [arangodb/spring-data#127]
Say I've defined a document entity (taken from [spring-data-demo](https://github.com/arangodb/spring-data-demo)

```java
@Document("characters")
@HashIndex(fields = { "name", "surname" }, unique = true)
public class Character {
	@Id
	private String id;
	private String name;
	private String surname;
	private boolean alive;
	private Integer age;
```

And we've inserted some documents using this definition.

Then we found more attributes are needed, for example:

```java
@Document("characters")
@HashIndex(fields = { "name", "surname" }, unique = true)
public class Character {
	@Id
	private String id;
	private String name;
	private String surname;
	private boolean alive;
	private Integer age;

        // added
	private boolean isMale = true;
```

Now exceptions are thrown when trying to read existing data (by `findById`, etc):

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.convertResult(ArangoResultConverter.java:122)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.convertResult(AbstractArangoQuery.java:189)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.execute(AbstractArangoQuery.java:82)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy51.findByNameAndSurname(Unknown Source)
	at com.arangodb.spring.demo.runner.TestRunner.run(TestRunner.java:57)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at com.arangodb.spring.demo.DemoApplication.main(DemoApplication.java:39)
Caused by: java.lang.NullPointerException
	at sun.invoke.util.ValueConversions.unboxBoolean(ValueConversions.java:103)
	at com.arangodb.spring.demo.entity.Character_Accessor_iofoar.setProperty(Unknown Source)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readProperty(DefaultArangoConverter.java:224)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.lambda$readEntity$0(DefaultArangoConverter.java:202)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:328)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readEntity(DefaultArangoConverter.java:199)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:179)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:130)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:89)
	at com.arangodb.springframework.core.template.ArangoExtCursorIterator.deserialize(ArangoExtCursorIterator.java:60)
	at com.arangodb.internal.cursor.ArangoCursorIterator.next(ArangoCursorIterator.java:75)
	at com.arangodb.internal.cursor.ArangoCursorImpl.next(ArangoCursorImpl.java:112)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.getNext(ArangoResultConverter.java:251)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.convertOptional(ArangoResultConverter.java:213)
	... 24 more
```

**Comment by mpv1989** [comment]
This is a bug with primitive types. I created a PR including a fix. #128

**Comment by lotabout** [comment]
WoW, such a quick move. Thanks!

**Comment by mpv1989** [comment]
version `3.2.0` released which contains the fix, can we close this issue?
