### ISSUE TITLE
Unsupported Map type: java.lang.Object

### ISSUE THREAD

**Issue by nickcodefresh** [arangodb/spring-data#139]
Hi,

I've trying to load the following document using arangodb-spring-data v3.1.1 and Spring Boot 2 (and consequently Spring Framework v5.0.7):
```
{
  "metadata": {},
  "type": "asset",
  "objectId": 12019
}
```
When I do this I get the following error:
```
Caused by: java.lang.IllegalArgumentException: Unsupported Map type: java.lang.Object
	at org.springframework.core.CollectionFactory.createMap(CollectionFactory.java:316)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readMap(DefaultArangoConverter.java:264)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:167)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readMap(DefaultArangoConverter.java:277)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readBaseDocument(DefaultArangoConverter.java:497)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:163)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:130)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:89)
	at com.arangodb.springframework.core.template.ArangoExtCursorIterator.deserialize(ArangoExtCursorIterator.java:60)
	at com.arangodb.internal.cursor.ArangoCursorIterator.next(ArangoCursorIterator.java:75)
	at com.arangodb.internal.cursor.ArangoCursorImpl.next(ArangoCursorImpl.java:112)
	at com.ooyala.flex.metadata.persistence.arango.ArangoMetadataPersistence.read(ArangoMetadataPersistence.java:166)
	at tv.nativ.mio.metadata.persistence.MetadataPersistenceServiceImpl.getMetadataInstance(MetadataPersistenceServiceImpl.java:114)
	at com.ooyala.flex.fastobject.service.ArangoDbMetadataService.lambda$getMetadataInstance$0(ArangoDbMetadataService.java:51)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:143)
	at com.ooyala.flex.fastobject.service.ArangoDbMetadataService.getMetadataInstance(ArangoDbMetadataService.java:50)
	... 72 common frames omitted
```
If I delete `"metadata": {},` from the source document then it loads fine. This seems a pretty simple use case to me, so any ideas what's going on?

I should say that this used to work fine when running on Spring Boot 1.5 and arangodb-spring-data v1.3.1.

Thanks

Nick

**Comment by mpv1989** [comment]
would be fixed with PR #135

**Comment by nickcodefresh** [comment]
I tried the code in your fork (https://github.com/mpv1989/spring-data), but I still get the issue.

**Comment by nickcodefresh** [comment]
It's ok I figured it out. We're not using Spring Data Arango and annotated classes to load documents, so this will never work.
