### ISSUE TITLE
ClassCastException when saving entity with non-string Id.

### ISSUE THREAD

**Issue by sonbt56** [arangodb/spring-data#150]
**arangodb-spring-data** version **3.2.1**

I have simple entity class like this.

```
@Document("role")
@HashIndex(fields = { "name" }, unique = true)
public class Role implements GrantedAuthority {

    @Id
    private Long id;

    private String name;
...
}
```

and repository interface:

```
public interface RoleRepository extends ArangoRepository<Role, Long> {
    Optional<Role> findByName(String name);
}

```

When ever I call roleRepository.save(roleEntity) it throws "_java.lang.ClassCastException: Cannot cast java.lang.String to java.lang.Long_"

at _com.arangodb.springframework.core.template.ArangoTemplate.updateDBFields(ArangoTemplate.java:720)_

If I change ID type from Long to String in both Entity class and Repository interface it can write data normally. Please take a look. Thanks

Stack trace:

```
java.lang.ClassCastException: Cannot cast java.lang.String to java.lang.Long
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361) ~[na:1.8.0_131]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356) ~[na:1.8.0_131]
	at com.esbt.conductorerp.app.model.Role_Accessor_fsyo6d.setProperty(Unknown Source) ~[main/:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.updateDBFields(ArangoTemplate.java:720) ~[arangodb-spring-data-3.2.1.jar:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.insert(ArangoTemplate.java:586) ~[arangodb-spring-data-3.2.1.jar:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.repsert(ArangoTemplate.java:688) ~[arangodb-spring-data-3.2.1.jar:na]
	at com.arangodb.springframework.repository.SimpleArangoRepository.save(SimpleArangoRepository.java:89) ~[arangodb-spring-data-3.2.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at com.sun.proxy.$Proxy87.save(Unknown Source) ~[na:na]
```

**Comment by uouo690** [comment]
Use String instead of long for the id.

**Comment by rashtao** [comment]
According to the documentation this is supposed to work: https://github.com/arangodb/spring-data/blob/62bcf7e1ad1e334bfae61b43e9f53584bbd44405/docs/Drivers/SpringData/Migration/Migrating-2.x-3.0.md#annotations-id

I have also created a failing test to reproduce the issue here: https://github.com/arangodb/spring-data/blob/c20e796efd7a4bc31534effbb0d6a1e72d1bac81/src/test/java/com/arangodb/springframework/debug/repository/LongEntityRepositoryTest.java

**Comment by rashtao** [comment]
Fixed since https://github.com/arangodb/spring-data/commit/6896ddc8a9d89284aa98044e80ab2c0a20aebdc0
