### ISSUE TITLE
SimpleArangoRepository.save() fails with Error: 1466 - must not specify _key for this collection

### ISSUE THREAD

**Issue by oliverlockwood** [arangodb/spring-data#185]
From digging into this, the problem is exposed in the following scenario:
* running Arango in a cluster, not single-instance
* The underlying Arango collection uses a custom shard key (which is itself necessary to allow configuration of a custom unique hash index - see #173)
* ArangoDB version is >= 3.4.0

I am running with:
-  `arangodb-spring-data`, version 3.2.3
-  `arangodb-java-driver`, version 6.6.2
-  ArangoDB itself, version 3.6.3.

Note that our domain object has the following annotations (I'm using Lombok for a couple of these):
```java
@EqualsAndHashCode
@Data
@Document(value = "myCollectionName", shardKeys = "myCustomId")
@HashIndex(fields = { "myCustomId" }, unique = true)
public class MyClassName implements Serializable {

    private static final long serialVersionUID = 1L;

    @ArangoId
    private String id;

    @Id
    private String key;

    private long documentVersion = 1L;
    private long myCustomId;
    ... other fields ...
}
```

As per the code in https://github.com/arangodb/spring-data/blob/master/src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java#L86-L90, the `save()` method end up calling repsert().  It fails every time with a stack trace like this:

```
org.springframework.dao.InvalidDataAccessApiUsageException: Response: 400, Error: 1466 - must not specify _key for this collection; nested exception is com.arangodb.ArangoDBException: Response: 400, Error: 1466 - must not specify _key for this collection
    at com.arangodb.springframework.core.util.ArangoExceptionTranslator.translateExceptionIfPossible(ArangoExceptionTranslator.java:57)
    at com.arangodb.springframework.core.template.ArangoTemplate.insert(ArangoTemplate.java:583)
    at com.arangodb.springframework.core.template.ArangoTemplate.repsert(ArangoTemplate.java:688)
    at com.arangodb.springframework.repository.SimpleArangoRepository.save(SimpleArangoRepository.java:89)
    ... <truncated for brevity>
Caused by: com.arangodb.ArangoDBException: Response: 400, Error: 1466 - must not specify _key for this collection
    at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:52)
    at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:141)
    at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:126)
    at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)
    at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:124)
    at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)
    at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
    at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:61)
    at com.arangodb.internal.ArangoCollectionImpl.insertDocument(ArangoCollectionImpl.java:56)
    at com.arangodb.springframework.core.template.ArangoTemplate.insert(ArangoTemplate.java:581)
    ... 39 common frames omitted
```

The documentation at https://www.arangodb.com/docs/stable/release-notes-new-features34.html specifically says:
>Please note that in a cluster setup the Repsert operation requires the collection to be sharded by _key.

So from where I'm standing, this looks like a straight-up bug in spring-data-arangodb.

**Comment by oliverlockwood** [comment]
For anyone else experiencing this: I think it _may_ be possible to work around using something like this:

```java
package com.ooyala.flex.publishindexer.repository.arangodb;

import com.arangodb.springframework.core.ArangoOperations;
import com.arangodb.springframework.repository.SimpleArangoRepository;
import org.springframework.lang.NonNull;


/**
 * For ArangoDB 3.4.0 or later, the default {@link #save} and {@link #saveAll} methods provided by spring-data-arangodb
 * try to use the {@link ArangoOperations#repsert(Object)} methods.  In a clustered environment, this fails with
 * com.arangodb.ArangoDBException: Response: 400, Error: 1466 - must not specify _key for this collection
 *
 * See https://www.arangodb.com/docs/stable/release-notes-new-features34.html which specifically says:
 * <blockquote>Please note that in a cluster setup the Repsert operation requires the collection to be sharded by _key.</blockquote>
 *
 * We have raised ticket https://github.com/arangodb/spring-data/issues/185, but in the meantime we work around with
 * this implementation.
 */
@Slf4j
public class AbstractCustomRepositoryImpl<T> extends SimpleArangoRepository<T, String> {

    private final ArangoOperations arangoOperations;

    protected AbstractCustomRepositoryImpl(final ArangoOperations arangoOperations, final Class<T> domainClass) {
        super(arangoOperations, domainClass);
        this.arangoOperations = arangoOperations;
    }

    @SuppressWarnings("deprecation")
    @Override
    public @NonNull <S extends T> S save(@NonNull S entity) {

        arangoOperations.upsert(entity, ArangoOperations.UpsertStrategy.REPLACE);

        return entity;
    }


    @SuppressWarnings("deprecation")
    @Override
    public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {

        arangoOperations.upsert(entities, ArangoOperations.UpsertStrategy.REPLACE);

        return entities;
    }

}
```

and then adding concrete implementations for each of your domain classes.  However, I've not tested this; I imagine some fiddling around with Spring wiring would need to be done also.

Anyway, it's still a bug, so I'm keeping this ticket open.

**Comment by joerg84** [comment]
Thanks, we are looking into this.

**Comment by rashtao** [comment]
@oliverlockwood thanks for reporting.
It should be fixed by https://github.com/arangodb/spring-data/pull/192 , can you please check if it fixes also your case?

**Comment by oliverlockwood** [comment]
@rashtao from code reading, it's certainly plausible that your change would fix the issue.  However I'm afraid that I'm not in a position at the moment to be able to explicitly build the code and test the PR for you 😄
