### ISSUE TITLE
NullPointerException when Deactivating type mapping

### ISSUE THREAD

**Issue by Joalien** [arangodb/spring-data#210]
To deactivate the type mapping, the documentation advises to set `typeKey` to null

As explained [in the documentation](https://www.arangodb.com/docs/stable/drivers/spring-data-reference-mapping.html#deactivating-type-mapping)
> deactivating type mapping may lead to exceptions when reading the entities from the DB.

In the method `com.arangodb.springframework.core.convert.DefaultArangoTypeMapper.DefaultTypeAliasAccessor#readAliasFrom`, the call `source.get(this.typeKey);` throws a `NullPointerException` when `this.typeKey` is null. I suggest to add a non-null check before

_before_
```java
if (source.isObject()) {
    final VPackSlice typeKey = source.get(this.typeKey);
    return Alias.ofNullable(typeKey.isString() ? typeKey.getAsString() : null);
}
```

_after_
```java
if (source.isObject()) {
    if (this.typeKey == null) return Alias.NONE;
    final VPackSlice typeKey = source.get(this.typeKey);
    return Alias.ofNullable(typeKey.isString() ? typeKey.getAsString() : null);
}
```

[Here](https://github.com/arangodb/spring-data/pull/212) is the linked pull request

**Comment by rashtao** [comment]
`VPackSlice.get(String)` does not require a non-null argument. In such case it should return a `VPackSlice.NONE_SLICE`.
 Can you please provide the stacktrace of the exception? Or can you include a test in your PR?

**Comment by Joalien** [comment]
Here is my stacktrace : 

```
java.lang.NullPointerException
	at java.lang.String.compareTo(String.java:1155)
	at com.arangodb.velocypack.VPackSlice.compareString(VPackSlice.java:757)
	at com.arangodb.velocypack.VPackSlice.searchObjectKeyBinary(VPackSlice.java:585)
	at com.arangodb.velocypack.VPackSlice.get(VPackSlice.java:524)
	at com.arangodb.springframework.core.convert.DefaultArangoTypeMapper$DefaultTypeAliasAccessor.readAliasFrom(DefaultArangoTypeMapper.java:183)
	at com.arangodb.springframework.core.convert.DefaultArangoTypeMapper.readType(DefaultArangoTypeMapper.java:97)
	at com.arangodb.springframework.core.convert.DefaultArangoTypeMapper.readType(DefaultArangoTypeMapper.java:105)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:141)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:129)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:88)
	at com.arangodb.springframework.core.template.ArangoExtCursorIterator.deserialize(ArangoExtCursorIterator.java:60)
	at com.arangodb.internal.cursor.ArangoCursorIterator.next(ArangoCursorIterator.java:75)
	at com.arangodb.internal.cursor.ArangoCursorImpl.next(ArangoCursorImpl.java:112)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.getNext(ArangoResultConverter.java:251)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.convertResult(ArangoResultConverter.java:120)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.convertResult(AbstractArangoQuery.java:189)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.execute(AbstractArangoQuery.java:82)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy97.findUserByUsername(Unknown Source)
        ...
```

**Comment by rashtao** [comment]
The stacktrace does not seem to be related to `com.arangodb:velocypack:2.4.1`. Can you please check which version of `com.arangodb:velocypack` you are using?

**Comment by Joalien** [comment]
Indeed, I was using `com.arangodb:velocypack:1.4.1`.
I updated velocypack version and here is the stackstrace : 
```
java.lang.NullPointerException
	at com.arangodb.velocypack.VPackSlice.searchObjectKeyBinary(VPackSlice.java:698)
	at com.arangodb.velocypack.VPackSlice.get(VPackSlice.java:649)
	at com.arangodb.springframework.core.convert.DefaultArangoTypeMapper$DefaultTypeAliasAccessor.readAliasFrom(DefaultArangoTypeMapper.java:183)
	at com.arangodb.springframework.core.convert.DefaultArangoTypeMapper.readType(DefaultArangoTypeMapper.java:97)
	at com.arangodb.springframework.core.convert.DefaultArangoTypeMapper.readType(DefaultArangoTypeMapper.java:105)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:126)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:114)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:73)
	at com.arangodb.springframework.core.template.ArangoExtCursorIterator.deserialize(ArangoExtCursorIterator.java:60)
	at com.arangodb.internal.cursor.ArangoCursorIterator.next(ArangoCursorIterator.java:74)
	at com.arangodb.internal.cursor.ArangoCursorImpl.next(ArangoCursorImpl.java:111)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.getNext(ArangoResultConverter.java:251)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.convertResult(ArangoResultConverter.java:120)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.convertResult(AbstractArangoQuery.java:189)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.execute(AbstractArangoQuery.java:82)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy97.findUserByUsername(Unknown Source)
```

**Comment by rashtao** [comment]
Thanks for reporting, I see the problem now! 
`VPackSlice.get(null)` returns from some if-else branches `VPackSlice.NONE_SLICE` and from others throws NPE. 
I fixed [here](https://github.com/arangodb/java-velocypack/commit/9b89b8ad1042e942ed42a89e6340ccf2a62e610f), a patch release will follow soon.

**Comment by rashtao** [comment]
fix released: https://github.com/arangodb/spring-data/releases/tag/v3.4.0
