### ISSUE TITLE
Arango directly print stacktrace on stderr bypassing logger and making client unable to deal with error

### ISSUE THREAD

**Issue by Joalien** [arangodb/spring-data#213]
In `spring-data/src/main/java/com/arangodb/springframework/repository/query/ArangoResultConverter.java#convertResult`

```java
public Object convertResult(final Class<?> type) {
		try {
			if (type.isArray()) {
				return TYPE_MAP.get("array").invoke(this);
			}
			if (!TYPE_MAP.containsKey(type)) {
				return getNext(result);
			}
			return TYPE_MAP.get(type).invoke(this);
		} catch (final Exception e) { // HERE
		        e.printStackTrace(); // HERE
			return null;
		}
	}
```
This function has two major problems :
- On the first hand, it prints an error on stderr, preventing to use appropriate logger.
- On the other hand, catching the exception and returning null prevents clients to deal with errors as it does not know about the errors.

For example, I had in Arango a enum key that I didn't have in my backend (_so the mapping failed  cf. stacktrace_). I want to be able to process that Exception. Instead, I have a `null` with no Exception flow (as it does not throw Exception, I cannot catch it so I cannot know that something bad happened). Furthermore, `null` does not contain any error message so my code is **unable** to know what was wrong.

What I suggest is to remove the try-catch and let clients process the exception - _which will solve at the  same time the logger problem_

_This is print in stderr_
```
java.lang.IllegalArgumentException: No enum constant my.custom.enum.TOTO
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readSimple(DefaultArangoConverter.java:446)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:154)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readPropertyValue(DefaultArangoConverter.java:259)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readProperty(DefaultArangoConverter.java:227)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.lambda$readEntity$0(DefaultArangoConverter.java:205)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:355)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readEntity(DefaultArangoConverter.java:202)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:182)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readCollection(DefaultArangoConverter.java:304)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:178)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readPropertyValue(DefaultArangoConverter.java:259)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readProperty(DefaultArangoConverter.java:227)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.lambda$readEntity$0(DefaultArangoConverter.java:205)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:355)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readEntity(DefaultArangoConverter.java:202)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.readInternal(DefaultArangoConverter.java:182)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:129)
	at com.arangodb.springframework.core.convert.DefaultArangoConverter.read(DefaultArangoConverter.java:88)
	at com.arangodb.springframework.core.template.ArangoExtCursorIterator.deserialize(ArangoExtCursorIterator.java:60)
	at com.arangodb.internal.cursor.ArangoCursorIterator.next(ArangoCursorIterator.java:75)
	at com.arangodb.internal.cursor.ArangoCursorImpl.next(ArangoCursorImpl.java:112)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.getNext(ArangoResultConverter.java:251)
	at com.arangodb.springframework.repository.query.ArangoResultConverter.convertResult(ArangoResultConverter.java:120)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.convertResult(AbstractArangoQuery.java:189)
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.execute(AbstractArangoQuery.java:82)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
```

**Comment by rashtao** [comment]
Thanks for reporting, fixed in https://github.com/arangodb/spring-data/commit/7e948588ac49c48fdcb2767f48f55f0371caccf1
