### ISSUE TITLE
@query in a repository generates ClassCastException

### ISSUE THREAD

**Issue by Sinisterish** [arangodb/spring-data#29]
I use this code to generate a repository just for some  queries which are supposed to be generic
as i on run-time decide the query and building a repository class for each collection is tidies and long process 
i just tried an example to see if i get a response back, as i wasn't sure if you can do a repository of object 
funny part the query executes and returns data when i debug but i get a ClassCastException after the query executes 

`public interface GenericArangoRepo extends ArangoRepository<Object>{

	@Query("FOR pv IN PV return pv")
	Object listPVs();
}`

## stack trace

Caused by: java.lang.ClassCastException: Cannot cast com.arangodb.internal.ArangoCursorIterator to com.arangodb.springframework.core.template.ArangoExtCursorIterator
	at java.lang.Class.cast(Class.java:3369) ~[na:1.8.0_161]
	at com.arangodb.springframework.core.template.ArangoExtCursor.<init>(ArangoExtCursor.java:41) ~[arangodb-spring-data-1.0.0.jar:na]
	at com.arangodb.springframework.core.template.ArangoCursorInitializer.createInstance(ArangoCursorInitializer.java:48) ~[arangodb-spring-data-1.0.0.jar:na]
	at com.arangodb.ArangoDatabase.createCursor(ArangoDatabase.java:334) ~[arangodb-java-driver-4.2.2.jar:na]
	at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:301) ~[arangodb-java-driver-4.2.2.jar:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.query(ArangoTemplate.java:314) ~[arangodb-spring-data-1.0.0.jar:na]
	at com.arangodb.springframework.repository.query.ArangoAqlQuery.execute(ArangoAqlQuery.java:188) ~[arangodb-spring-data-1.0.0.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:499) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:477) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.sun.proxy.$Proxy53.bulkCommitItems(Unknown Source) ~[na:na]
	at arangoboot.BulkRunner.run(BulkRunner.java:21) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	... 5 common frames omitted

**Comment by christian-lechner** [comment]
`Object` is not a supported return type. Please see the [return types section](https://github.com/arangodb/spring-data#return-types) in the README for a list of supported return types.

**Comment by Sinisterish** [comment]
change to this
and the exception still occurs 

`public interface GenericArangoRepo extends Repository<BaseDocument, String>{

	@Query("FOR vcenter IN PV return vcenter")
	ArangoCursor<BaseDocument> listPVs(@BindVars Map<String,Object> bindvars);

}`

## stack trace
Caused by: java.lang.ClassCastException: Cannot cast com.arangodb.internal.ArangoCursorIterator to com.arangodb.springframework.core.template.ArangoExtCursorIterator
	at java.lang.Class.cast(Class.java:3369) ~[na:1.8.0_161]
	at com.arangodb.springframework.core.template.ArangoExtCursor.<init>(ArangoExtCursor.java:41) ~[arangodb-spring-data-1.0.0.jar:na]
	at com.arangodb.springframework.core.template.ArangoCursorInitializer.createInstance(ArangoCursorInitializer.java:48) ~[arangodb-spring-data-1.0.0.jar:na]
	at com.arangodb.ArangoDatabase.createCursor(ArangoDatabase.java:334) ~[arangodb-java-driver-4.2.2.jar:na]
	at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:301) ~[arangodb-java-driver-4.2.2.jar:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.query(ArangoTemplate.java:314) ~[arangodb-spring-data-1.0.0.jar:na]
	at com.arangodb.springframework.repository.query.ArangoAqlQuery.execute(ArangoAqlQuery.java:188) ~[arangodb-spring-data-1.0.0.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:499) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:477) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.sun.proxy.$Proxy53.listPVs(Unknown Source) ~[na:na]
	at arangoboot.BulkRunner.run(BulkRunner.java:21) ~[classes/:na]

**Comment by mpv1989** [comment]
@Sinisterish this looks like you are using incompatible versions of `arangodb-java-driver` and `arangodb-spring-data`.

The newest version of `arangodb-spring-data` is `1.0.2` and `2.0.3` (depending on the Spring Data version you are using) and the current version of `arangodb-java-driver` is `4.3.4`.

best
Mark
