### ISSUE TITLE
Support spring boot 3.2.0

### ISSUE THREAD

**Issue by maymaewa** [arangodb/spring-data#292]
Hello! I update my module with ArangoDB to spring boot from 3.1.5 to 3.2.0 and get error:

```
java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getTypeForFactoryBeanFromAttributes(FactoryBeanRegistrySupport.java:86)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:838)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:620)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:573)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:775)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:597)
	at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:228)
	at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:105)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:212)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
```
	
```
[INFO] +- com.arangodb:arangodb-spring-data:jar:4.0.0:compile
[INFO] |  +- org.springframework:spring-tx:jar:6.0.10:compile
[INFO] |  \- org.springframework.data:spring-data-commons:jar:3.0.7:compile
```

This error occurs when trying to initialize my arango **PersonRepository**, since the behavior of the getTypeForFactoryBeanFromAttributes method has changed in the new boot version.

My problem is resolved by updating spring-data-commons from 3.0.7 to 3.2.0. This dependency comes from arangodb-spring-data

So, please, update this dependency in arangodb-spring-data for adding spring boot 3.2.0 support

Thank you!

**Comment by rashtao** [comment]
fixed in https://github.com/arangodb/spring-data/releases/tag/v4.1.0
